# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: callback-action
  namespace: callback-action
  labels:
    app: callback-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callback-action
  template:
    metadata:
      labels:
        app: callback-action
    spec:
      serviceAccount: ${env_prefix}callback-action-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: callback-action
          image: "${location}-docker.pkg.dev/${project}/${repository}/callback-action-service:latest"
          env:
            - name: CONFIG
              value: "/config/config.json"
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: /config/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: callback-action-config
